# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cimex/Projects/Computer_Graphics/verlet_integration

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cimex/Projects/Computer_Graphics/verlet_integration

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cimex/Projects/Computer_Graphics/verlet_integration/CMakeFiles /home/cimex/Projects/Computer_Graphics/verlet_integration//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cimex/Projects/Computer_Graphics/verlet_integration/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named verlet_integration

# Build rule for target.
verlet_integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 verlet_integration
.PHONY : verlet_integration

# fast build rule for target.
verlet_integration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/build
.PHONY : verlet_integration/fast

#=============================================================================
# Target rules for targets named shader

# Build rule for target.
shader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shader
.PHONY : shader

# fast build rule for target.
shader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shader.dir/build.make CMakeFiles/shader.dir/build
.PHONY : shader/fast

dependencies/imgui/imgui.o: dependencies/imgui/imgui.cpp.o
.PHONY : dependencies/imgui/imgui.o

# target to build an object file
dependencies/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui.cpp.o
.PHONY : dependencies/imgui/imgui.cpp.o

dependencies/imgui/imgui.i: dependencies/imgui/imgui.cpp.i
.PHONY : dependencies/imgui/imgui.i

# target to preprocess a source file
dependencies/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui.cpp.i
.PHONY : dependencies/imgui/imgui.cpp.i

dependencies/imgui/imgui.s: dependencies/imgui/imgui.cpp.s
.PHONY : dependencies/imgui/imgui.s

# target to generate assembly for a file
dependencies/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui.cpp.s
.PHONY : dependencies/imgui/imgui.cpp.s

dependencies/imgui/imgui_demo.o: dependencies/imgui/imgui_demo.cpp.o
.PHONY : dependencies/imgui/imgui_demo.o

# target to build an object file
dependencies/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_demo.cpp.o
.PHONY : dependencies/imgui/imgui_demo.cpp.o

dependencies/imgui/imgui_demo.i: dependencies/imgui/imgui_demo.cpp.i
.PHONY : dependencies/imgui/imgui_demo.i

# target to preprocess a source file
dependencies/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_demo.cpp.i
.PHONY : dependencies/imgui/imgui_demo.cpp.i

dependencies/imgui/imgui_demo.s: dependencies/imgui/imgui_demo.cpp.s
.PHONY : dependencies/imgui/imgui_demo.s

# target to generate assembly for a file
dependencies/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_demo.cpp.s
.PHONY : dependencies/imgui/imgui_demo.cpp.s

dependencies/imgui/imgui_draw.o: dependencies/imgui/imgui_draw.cpp.o
.PHONY : dependencies/imgui/imgui_draw.o

# target to build an object file
dependencies/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_draw.cpp.o
.PHONY : dependencies/imgui/imgui_draw.cpp.o

dependencies/imgui/imgui_draw.i: dependencies/imgui/imgui_draw.cpp.i
.PHONY : dependencies/imgui/imgui_draw.i

# target to preprocess a source file
dependencies/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_draw.cpp.i
.PHONY : dependencies/imgui/imgui_draw.cpp.i

dependencies/imgui/imgui_draw.s: dependencies/imgui/imgui_draw.cpp.s
.PHONY : dependencies/imgui/imgui_draw.s

# target to generate assembly for a file
dependencies/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_draw.cpp.s
.PHONY : dependencies/imgui/imgui_draw.cpp.s

dependencies/imgui/imgui_impl_glfw.o: dependencies/imgui/imgui_impl_glfw.cpp.o
.PHONY : dependencies/imgui/imgui_impl_glfw.o

# target to build an object file
dependencies/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_impl_glfw.cpp.o
.PHONY : dependencies/imgui/imgui_impl_glfw.cpp.o

dependencies/imgui/imgui_impl_glfw.i: dependencies/imgui/imgui_impl_glfw.cpp.i
.PHONY : dependencies/imgui/imgui_impl_glfw.i

# target to preprocess a source file
dependencies/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_impl_glfw.cpp.i
.PHONY : dependencies/imgui/imgui_impl_glfw.cpp.i

dependencies/imgui/imgui_impl_glfw.s: dependencies/imgui/imgui_impl_glfw.cpp.s
.PHONY : dependencies/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
dependencies/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_impl_glfw.cpp.s
.PHONY : dependencies/imgui/imgui_impl_glfw.cpp.s

dependencies/imgui/imgui_impl_opengl3.o: dependencies/imgui/imgui_impl_opengl3.cpp.o
.PHONY : dependencies/imgui/imgui_impl_opengl3.o

# target to build an object file
dependencies/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_impl_opengl3.cpp.o
.PHONY : dependencies/imgui/imgui_impl_opengl3.cpp.o

dependencies/imgui/imgui_impl_opengl3.i: dependencies/imgui/imgui_impl_opengl3.cpp.i
.PHONY : dependencies/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
dependencies/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_impl_opengl3.cpp.i
.PHONY : dependencies/imgui/imgui_impl_opengl3.cpp.i

dependencies/imgui/imgui_impl_opengl3.s: dependencies/imgui/imgui_impl_opengl3.cpp.s
.PHONY : dependencies/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
dependencies/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_impl_opengl3.cpp.s
.PHONY : dependencies/imgui/imgui_impl_opengl3.cpp.s

dependencies/imgui/imgui_tables.o: dependencies/imgui/imgui_tables.cpp.o
.PHONY : dependencies/imgui/imgui_tables.o

# target to build an object file
dependencies/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_tables.cpp.o
.PHONY : dependencies/imgui/imgui_tables.cpp.o

dependencies/imgui/imgui_tables.i: dependencies/imgui/imgui_tables.cpp.i
.PHONY : dependencies/imgui/imgui_tables.i

# target to preprocess a source file
dependencies/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_tables.cpp.i
.PHONY : dependencies/imgui/imgui_tables.cpp.i

dependencies/imgui/imgui_tables.s: dependencies/imgui/imgui_tables.cpp.s
.PHONY : dependencies/imgui/imgui_tables.s

# target to generate assembly for a file
dependencies/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_tables.cpp.s
.PHONY : dependencies/imgui/imgui_tables.cpp.s

dependencies/imgui/imgui_widgets.o: dependencies/imgui/imgui_widgets.cpp.o
.PHONY : dependencies/imgui/imgui_widgets.o

# target to build an object file
dependencies/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_widgets.cpp.o
.PHONY : dependencies/imgui/imgui_widgets.cpp.o

dependencies/imgui/imgui_widgets.i: dependencies/imgui/imgui_widgets.cpp.i
.PHONY : dependencies/imgui/imgui_widgets.i

# target to preprocess a source file
dependencies/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_widgets.cpp.i
.PHONY : dependencies/imgui/imgui_widgets.cpp.i

dependencies/imgui/imgui_widgets.s: dependencies/imgui/imgui_widgets.cpp.s
.PHONY : dependencies/imgui/imgui_widgets.s

# target to generate assembly for a file
dependencies/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/dependencies/imgui/imgui_widgets.cpp.s
.PHONY : dependencies/imgui/imgui_widgets.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/factory.o: src/factory.cpp.o
.PHONY : src/factory.o

# target to build an object file
src/factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/factory.cpp.o
.PHONY : src/factory.cpp.o

src/factory.i: src/factory.cpp.i
.PHONY : src/factory.i

# target to preprocess a source file
src/factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/factory.cpp.i
.PHONY : src/factory.cpp.i

src/factory.s: src/factory.cpp.s
.PHONY : src/factory.s

# target to generate assembly for a file
src/factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/factory.cpp.s
.PHONY : src/factory.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/gui.o: src/gui.cpp.o
.PHONY : src/gui.o

# target to build an object file
src/gui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/gui.cpp.o
.PHONY : src/gui.cpp.o

src/gui.i: src/gui.cpp.i
.PHONY : src/gui.i

# target to preprocess a source file
src/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/gui.cpp.i
.PHONY : src/gui.cpp.i

src/gui.s: src/gui.cpp.s
.PHONY : src/gui.s

# target to generate assembly for a file
src/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/gui.cpp.s
.PHONY : src/gui.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/particle.o: src/particle.cpp.o
.PHONY : src/particle.o

# target to build an object file
src/particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/particle.cpp.o
.PHONY : src/particle.cpp.o

src/particle.i: src/particle.cpp.i
.PHONY : src/particle.i

# target to preprocess a source file
src/particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/particle.cpp.i
.PHONY : src/particle.cpp.i

src/particle.s: src/particle.cpp.s
.PHONY : src/particle.s

# target to generate assembly for a file
src/particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/particle.cpp.s
.PHONY : src/particle.cpp.s

src/render.o: src/render.cpp.o
.PHONY : src/render.o

# target to build an object file
src/render.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/render.cpp.o
.PHONY : src/render.cpp.o

src/render.i: src/render.cpp.i
.PHONY : src/render.i

# target to preprocess a source file
src/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/render.cpp.i
.PHONY : src/render.cpp.i

src/render.s: src/render.cpp.s
.PHONY : src/render.s

# target to generate assembly for a file
src/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/render.cpp.s
.PHONY : src/render.cpp.s

src/shader.o: src/shader.cpp.o
.PHONY : src/shader.o

# target to build an object file
src/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/shader.cpp.o
.PHONY : src/shader.cpp.o

src/shader.i: src/shader.cpp.i
.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s
.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verlet_integration.dir/build.make CMakeFiles/verlet_integration.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shader"
	@echo "... verlet_integration"
	@echo "... dependencies/imgui/imgui.o"
	@echo "... dependencies/imgui/imgui.i"
	@echo "... dependencies/imgui/imgui.s"
	@echo "... dependencies/imgui/imgui_demo.o"
	@echo "... dependencies/imgui/imgui_demo.i"
	@echo "... dependencies/imgui/imgui_demo.s"
	@echo "... dependencies/imgui/imgui_draw.o"
	@echo "... dependencies/imgui/imgui_draw.i"
	@echo "... dependencies/imgui/imgui_draw.s"
	@echo "... dependencies/imgui/imgui_impl_glfw.o"
	@echo "... dependencies/imgui/imgui_impl_glfw.i"
	@echo "... dependencies/imgui/imgui_impl_glfw.s"
	@echo "... dependencies/imgui/imgui_impl_opengl3.o"
	@echo "... dependencies/imgui/imgui_impl_opengl3.i"
	@echo "... dependencies/imgui/imgui_impl_opengl3.s"
	@echo "... dependencies/imgui/imgui_tables.o"
	@echo "... dependencies/imgui/imgui_tables.i"
	@echo "... dependencies/imgui/imgui_tables.s"
	@echo "... dependencies/imgui/imgui_widgets.o"
	@echo "... dependencies/imgui/imgui_widgets.i"
	@echo "... dependencies/imgui/imgui_widgets.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/factory.o"
	@echo "... src/factory.i"
	@echo "... src/factory.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/gui.o"
	@echo "... src/gui.i"
	@echo "... src/gui.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/particle.o"
	@echo "... src/particle.i"
	@echo "... src/particle.s"
	@echo "... src/render.o"
	@echo "... src/render.i"
	@echo "... src/render.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

